# Generated by Django 3.2.7 on 2021-10-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_time', models.IntegerField(max_length=6)),
                ('b_content', models.TextField()),
                ('b_auther', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
