# Generated by Django 3.2.7 on 2021-10-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrage', '0002_test_b_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('v_ad', models.CharField(max_length=50)),
                ('v_pic', models.CharField(max_length=50)),
                ('v_auther', models.CharField(max_length=20)),
                ('v_play', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='b_time',
            field=models.IntegerField(),
        ),
    ]
