# Generated by Django 3.2.7 on 2021-10-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrage', '0003_auto_20211021_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='v_title',
            field=models.CharField(default='default title', max_length=50),
        ),
    ]
