# Generated by Django 3.2.7 on 2021-10-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrage', '0004_video_v_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='v_id',
            field=models.IntegerField(default=1),
        ),
    ]
