# Generated by Django 3.2.7 on 2021-10-25 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barrage', '0008_video_v_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='v_time',
        ),
    ]
