# Generated by Django 3.2.7 on 2021-10-25 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barrage', '0009_remove_video_v_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='v_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
