# Generated by Django 3.2.7 on 2021-10-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrage', '0010_video_v_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
