# Generated by Django 3.2.7 on 2021-10-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrage', '0011_video_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='v_duaring',
            field=models.IntegerField(default=0),
        ),
    ]
