# Generated by Django 3.2.7 on 2021-10-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='picture',
            field=models.CharField(default='default.jpg', max_length=20),
        ),
    ]
