# Generated by Django 3.2.7 on 2021-10-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='picture',
            field=models.CharField(default='default.png', max_length=20),
        ),
    ]
