# Generated by Django 3.2.7 on 2021-10-27 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appuser_fans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuser',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
