# Generated by Django 3.2.7 on 2021-10-12 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=20, verbose_name='密码')),
                ('hash_password', models.CharField(blank=True, max_length=128, null=True, verbose_name='哈希密码')),
                ('user_gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '保密')], max_length=9, verbose_name='性别')),
                ('user_email', models.CharField(max_length=100, unique=True, verbose_name='邮箱')),
                ('register_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册日期')),
            ],
        ),
    ]
